### ISSUE TITLE
31-tet accidentals

### ISSUE THREAD

**Issue by AshtarBalynestjar** [euwbah/musescore-n-tet-plugins#1]
The accidentals here proposed don’t line up with the usual practice for 31-tet. Usually, arrows indicate shifts by a syntonic comma of 81:80, an interval that is tempered out by 31. The most common system of accidentals I’ve seen is:

bb - 4 steps down
db - 3 steps down
b - 2 steps down
d - 1 step down

ǂ - 1 step up
ǂǂ - 2 steps up
ǂǂǂ - 3 steps up
x - 4 steps up

**Comment by euwbah** [comment]
Thanks for letting me know, I just found out about the conflicts this accidental system has with the Helmholtz-Ellis just intonation standard.


Do note that the usage of the arrows attached to the accidentals are actually used to mimic the [up and downs notation](http://xenharmonic.wikispaces.com/Ups+and+Downs+Notation) that I've seen Fabio Costa use in his scores. Musescore doesn't actually have any accidentals that are remotely similar to the up and downs system so I naively used the accidentals with arrows appended to them as a substitute.


Of course this would be confusing for those who are already familiar with the Helmholtz-Ellis just intonation notation standard and I shall definitely provide options for selecting between accidental conventions once I'm done with my college exams, prolly in a month or so.

A bit off topic here, but one thing that still bothers me in the quarter-comma-meantone-esque system that you’ve mentioned, is the lack of 5-diesis-wide enharmonics.

For example, in the key of C, I would notate the 7:4 septimal seventh as either Bdb in the conventional system or Bbv in the up and downs system, both of which make sense. It could also be notated as A# but that would make it appear as a Neapolitan augmented 6th, which may or may not be enharmonically correct depending on the context.

But that's fine, until when it comes to keys like Db major. If I were to notate the 7:4 septimal seventh in the +/- 5-diesis arrow system, it could appear as Cbb or B natural, the former's note names of which spells out a seventh (D-Cbb) and the latter a Neapolitan augmented sixth (D-B).

However doing so in the standard 4-diesis quarter-tone style would mean that there is only one way to notate the septimal seventh of Db, which is simply B natural, however this would only be enharmonically correct if the septimal seventh were to be used as a Neapolitan augmented sixth. There isn't a way to make the note names spell out a seventh.


Anyways this is just my personal enharmonically-nitpicky opinion so I shan't force it upon anyone :stuck_out_tongue:

**Comment by euwbah** [comment]
Alright this is fixed in 2530d3f58f2608a1bcbb2bbb42adbd6ba6f1ea5c with the new 1/4-comma meantone approximation mode (a separate QML file), sorry it took so long!
