### ISSUE TITLE
Pitch up/down plugins interact poorly with key signatures

### ISSUE THREAD

**Issue by ketsuban** [euwbah/musescore-n-tet-plugins#14]
1. Enable the `pitch up` and `pitch down` plugins. (I assume the `pitch up no dt` and `pitch down no dt` plugins will act the same, but with different accidentals.)
2. Create a new 31EDO manuscript in F major.
3. Write a C7 chord.
4. Select the B flat.
5. Attempt to transpose it up two edosteps.
6. Attempt to transpose it down one edostep, then up one edostep.

In step 5, the B returns to flat rather than ascending to B natural. (It will oscillate forever between B flat and B semiflat if you continue to activate the pitch-up functionality.) In step 6, transposing down one edostep correctly uses the sesquiflat accidental, but then going back up redundantly uses a flat accidental.

**Comment by euwbah** [comment]
Hi, the issue you are facing can be solved by using the text key signature annotation (see https://github.com/euwbah/musescore-n-tet-plugins#key-signatures).

If you place a system text containing the text `.......b` to represent a key signature that contains Bb, the accidentals after pitch up/down will be handled properly.

As of yet, there are no known ways around this, all key signatures, whether using only standard accidentals or custom microtonal key signatures, have to be annotated using the key signature text annotation for the plugin to function properly.
