### ISSUE TITLE
up and down with key signatures doesn't retune notes correctly

### ISSUE THREAD

**Issue by minerscale** [euwbah/musescore-n-tet-plugins#17]
Version: Musescore 3.5 Portable Appimage Ubuntu 20.04

When using the custom key signatures with a notehead selected (the plugin works fine with the note range selected), using the up  or down plugins will set the tuning of the note to 300.0 (I suspect it's actually higher or undefined, given this is the max value) and the note will not have any playback until the tuning value is reset.

It's very odd that this bug is only prevalent when the notehead itself is selected, and not when a range containing only the note is selected. Retuning sets the pitch to the correct value and this bug only affects playback.

the example:
![image](https://user-images.githubusercontent.com/20499616/95650181-a7b4a600-0b2d-11eb-97b5-5db147702ce2.png)
before up plugin is used on C (happens with every other note):
![image](https://user-images.githubusercontent.com/20499616/95650188-b4d19500-0b2d-11eb-997b-cec2b8f4e198.png)
after the up plugin on C:
![image](https://user-images.githubusercontent.com/20499616/95650197-bdc26680-0b2d-11eb-9c39-a203db341796.png)

Any ideas? Thank you :)

**Comment by minerscale** [comment]
~~Hi, I don't know what I have done but I can no longer reproduce the issue. Should I close the issue?~~

Nevermind, apparently specifying a reference pitch is required. The default of A4 = 440hz is not respected in that very specific case. So it's still a bug I think.

**Comment by FloraCanou** [comment]
<s>Reproducible in both 2.2.0 (latest) and 2.1.1 (before my contribution of custom tuning center). @euwbah </s>

Don't know how I tested and got to that false claim. Sorry.

**Comment by bluebear94** [comment]
I can also reproduce in 2.2.0.

**Comment by euwbah** [comment]
Turns out this was caused by a typo which was somehow syntactically permissible :upside_down_face:

**Comment by FloraCanou** [comment]
Ouch. Turns out it was still me who introduced it.

**Comment by euwbah** [comment]
Haha no worries, thank you for contributing! It indeed inspires me. :)

**Comment by minerscale** [comment]
So glad it's fixed! I'm really really impressed at how seamlessly this
plugin implements n-tet music. Thanks for making this!
