### ISSUE TITLE
Transpose-Up-31-TET-Meantone doesn't work!

### ISSUE THREAD

**Issue by ghost** [euwbah/musescore-n-tet-plugins#18]
I want to use the meantone notation for composing in 31-TET. However, transposing the pitches of individual notes (with meantone) only works downwards. When I click on the "Raise Pitch By 1 Step" button, nothing happens. I would love to use this plugin because it is more convenient to me than the Ups-and-Downs notation.
https://github.com/euwbah/musescore-n-tet-plugins/blob/master/legacy/Transpose-Up-31-TET-Meantone.qml

**Comment by FloraCanou** [comment]
To make things clear, this ups-and-downs notation plugin supports semiflats and semisharps, and in the case of 31et, it functions identically to the legacy "meantone notation". The step offsets in both systems are: 

- 0: natural
- +1: semisharp
- +2: sharp
- +3: sesquisharp
- +4: double sharp

Don't hesitate with the latest version :)

**Comment by ghost** [comment]
What do you mean? Are there going to be newer versions?

**Comment by FloraCanou** [comment]
The latest version refers to the current version, which contains the "meantone notation" functionality.

**Comment by euwbah** [comment]
Hi nikolan01! Apologies if the README was unclear, it is still a work in progress. As FloraCanou has said, the plugin file that you loaded / were using belongs to the older version of the plugin. Do activate the `pitch down.qml`, `pitch up.qml`, and `tune n-edo.qml` plugin files instead, which is the current working version of the plugin that supports most EDOs from 5-72. The rule of pythagorean apotome size would apply, thus the "meantone version" of 31 edo would be used.

Do note that in the current version of the plugin, and moving forward, 31 edo would not be the default edo, and you will have to specify the tuning system for the entire score by placing a system text (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd>) containing the text `31 edo` on the first bar, and the above tuning system would be in effect from that bar onwards.

65d12e8b36d1d21bd0dfc89b935e243f9ca50e5c solves the current issue where placing the downloaded project folder into the plugins folder would cause al the legacy plugin files to show up in the plugin manager as well.

**Comment by Wolf-SO** [comment]
> Hi nikolan01! Apologies if the README was unclear, it is still a work in progress. As FloraCanou has said, the plugin file that you loaded / were using belongs to the older version of the plugin. Do activate the `pitch down.qml`, `pitch up.qml`, and `tune n-edo.qml` plugin files instead, which is the current working version of the plugin that supports most EDOs from 5-72. The rule of pythagorean apotome size would apply, thus the "meantone version" of 31 edo would be used.
> 
> Do note that in the current version of the plugin, and moving forward, 31 edo would not be the default edo, and you will have to specify the tuning system for the entire score by placing a system text (Ctrl+Shift+T) containing the text `31 edo` on the first bar, and the above tuning system would be in effect from that bar onwards.
> 
> [65d12e8](https://github.com/euwbah/musescore-n-tet-plugins/commit/65d12e8b36d1d21bd0dfc89b935e243f9ca50e5c) solves the current issue where placing the downloaded project folder into the plugins folder would cause al the legacy plugin files to show up in the plugin manager as well.

Very helpful explanation. I tried the plugin and was confused why it seemingly didn't work. Now I know how to use it. The readme is so long that it's easy to miss the actual howto for starters.
