### ISSUE TITLE
Pitch up with arrows plugin fails silently

### ISSUE THREAD

**Issue by bluebear94** [euwbah/musescore-n-tet-plugins#24]
The pitch up with arrows plugin doesn't change the pitch at all, no matter what EDO the note being adjusted is in. Strangely enough, this only affects the pitch up with arrows plugin, not the corresponding pitch down plugin.

**Comment by FloraCanou** [comment]
Is this part of the 8va problem?

**Comment by bluebear94** [comment]
No, this happens even without the 8vas.

**Comment by AveryBW** [comment]
I have this issue too. Pitch up with arrows does nothing, while the 3 others are fine. using Musescore 3.6.2 x64 on Windows 10

**Comment by euwbah** [comment]
Thanks for informing me, this should be fixed in the latest update. Let me know if it is working :)
