### ISSUE TITLE
Key signature text does not seem to apply, but only to one staff

### ISSUE THREAD

**Issue by bluebear94** [euwbah/musescore-n-tet-plugins#25]
[test107.mscz.txt](https://github.com/euwbah/musescore-n-tet-plugins/files/5861378/test107.mscz.txt) (rename to test107.mscz)

Measures 118 – 119 in top staff: A recognized as Ab, E recognized as Eb, despite there being a key signature text. Strangely enough, this doesn't happen for the bottom staff.

Other than it possibly having to do with voices, I have no idea why this is happening.

**Comment by FloraCanou** [comment]
Reproducible in 2.1.1, 2.2.0 and 2.2.2.

**Comment by bluebear94** [comment]
As I mentioned previously, I think the bug has to do with voices. I've found a minimal example (B and E in measure 2 are tuned incorrectly).

[test_score.zip](https://github.com/euwbah/musescore-n-tet-plugins/files/6115220/test_score.zip) (change extension to .mscz)

**Comment by euwbah** [comment]
Thanks for pointing this out! Took me a while to find the issue. Should be fixed in version 2.2.6: https://github.com/euwbah/musescore-n-tet-plugins/commit/d35f7d8420ad1ce8e849199f6ea6677cdc8b0e76
