### ISSUE TITLE
Natural with up/down arrow doesn't retune correctly (both Gould and Helmholtz-Ellis)

### ISSUE THREAD

**Issue by awelotta** [euwbah/musescore-n-tet-plugins#26]
![image](https://user-images.githubusercontent.com/74327187/107126850-ec501400-6877-11eb-8ede-85824346cc05.png)
![image](https://user-images.githubusercontent.com/74327187/107126862-f6721280-6877-11eb-94f0-5512fca1a394.png)
The tuning offset is the same, even though it should compensate for a different MIDI value.

**Comment by FloraCanou** [comment]
It should have been fixed in 2.2.2.

**Comment by awelotta** [comment]
You're right. I just reinstalled it and it seems to be fixed.
