### ISSUE TITLE
None of the plugins respond to keyboard shortcuts

### ISSUE THREAD

**Issue by bootmii** [euwbah/musescore-n-tet-plugins#27]
Not the retuner, the up, the up with arrows, the down, or the down with arrows. What am I doing wrong?

**Comment by euwbah** [comment]
Hi, may I know if you have activated the plugins by checking the check box beside the plugin name in the list of plugins of the Plugin Manager?

![image](https://user-images.githubusercontent.com/7107290/115469730-c5469300-a267-11eb-951b-08be57c55c5c.png)

**Comment by euwbah** [comment]
closed due to inactivity
