### ISSUE TITLE
add to README instructions for how to set shortcuts for plugins

### ISSUE THREAD

**Issue by cmloegcmluin** [euwbah/musescore-n-tet-plugins#28]
It took me a while to figure it out myself. You can't set them in Edit -> Preferences -> Shortcuts. You have to set them in Plugins -> Plugin Manager -> pitch up -> Define Shortcut.

**Comment by cmloegcmluin** [comment]
This change to the README does not address my concerns, but no big deal. Thank you for this plugin! I think I will try to adapt it to work for Sagittal notation at some point.

**Comment by euwbah** [comment]
https://github.com/euwbah/musescore-n-tet-plugins/commit/b44b206f91e09957a8975c9ef28ab4c266e1fc8d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R36

Hi! Would this line be sufficient?

**Comment by cmloegcmluin** [comment]
Yes, thank you much! That is exactly what would have helped me when I was first learning the tool :)
