### ISSUE TITLE
Naturals and Sharps don't work

### ISSUE THREAD

**Issue by lapiscarrot** [euwbah/musescore-n-tet-plugins#30]
Only flats work, and everything including and after a natural or sharp doesn't transpose at all. I am running the current version of Musescore, and this occurs regardless of how I run the retuning qml. Am I doing something incorrectly?
![Ab](https://user-images.githubusercontent.com/60489119/120123856-579f5800-c17f-11eb-9e0f-a7e7abf06ced.png)
![Bb](https://user-images.githubusercontent.com/60489119/120123857-579f5800-c17f-11eb-97dc-091f567262dd.png)
![C](https://user-images.githubusercontent.com/60489119/120123858-5837ee80-c17f-11eb-8453-5fd87001e54b.png)
![D](https://user-images.githubusercontent.com/60489119/120123859-5837ee80-c17f-11eb-8fdd-5a7e921f5a50.png)

**Comment by FloraCanou** [comment]
What version of the plugin are you using? I tested in 2.2.0 and 2.2.6 and can't reproduce it.

**Comment by lapiscarrot** [comment]
Never mind, I restarted Musescore and updated it, and it's gone now.
