### ISSUE TITLE
"Pitch-Up" function not working correctly

### ISSUE THREAD

**Issue by AryamanJoshi** [euwbah/musescore-n-tet-plugins#31]
Hi! 
I found a tiny issue while trying to use your awesome plugin.
The _pitch-up_ function does not work as desired, even in EDOs like 5-EDO which has no accidentals, the function starts showing accidentals and goes all the way to double-sharp with 3 arrows. However, pitch down works completely fine. 
Example: 
![image](https://user-images.githubusercontent.com/89426052/130529640-34a32c4e-2c40-45e0-b992-1d43f6a602ab.png)

Thank you for this plugin! I've been using it for a long time, this issue just popped up randomly after I formatted my laptop.

**Comment by euwbah** [comment]
Hello! Thanks for bringing this up, sorry it took a while. It should be fixed now :)
