### ISSUE TITLE
Plugin crashes in 35 edo

### ISSUE THREAD

**Issue by jundurg** [euwbah/musescore-n-tet-plugins#33]
Thank you for providing the plugin, it's a game-changer!

I have a bug to report; in **35edo** using the tune-up function crashes every time when trying to tune-up a note that already has three arrows up.
35edo is sharp-0 but has 5 steps between all the white keys; it should go from ^^^ to v, but it might be looking for an accidental that does not do anything in sharp-0.

(Same thing also reverse, tuning down.)

I've also checked whether 28edo works; since there are only 4 steps, it does not crash, however, the newly reached white key is at first not tuned correctly (but corrects via re-tuning), so same behaviour as if I just had placed the note via mouse.
In 21edo, this issue does not happen.

Musescore 3.6.2.
Plugin vs. 2.2.8.

edit: Problem also occurs in the latest version of the plugin.

**Comment by euwbah** [comment]
Ah, i haven't properly tested sharp-0 tunings myself yet, seems like there's a bunch of edge cases i haven't settled. Thanks for highlighting this, I will work on it once I am more free!
