### ISSUE TITLE
"pitch down no dt" is unavailable in Musescore 3.6.2 Linux

### ISSUE THREAD

**Issue by tank-trax** [euwbah/musescore-n-tet-plugins#35]
Using Musescore 3.6.2 (Flatpak) on Linux Mint 20.2

musescore-microtonal-edo-plugin commit 73cf9c

![image](https://user-images.githubusercontent.com/41337033/157789399-dd298d38-5be4-4a38-9483-0ffce8bbbd37.png)

**Comment by tank-trax** [comment]
I see the error. The first line of **pitch down no dt.qml**

`nameimport QtQuick 2.1`

changing it to 

`import QtQuick 2.1`

and it appears

![image](https://user-images.githubusercontent.com/41337033/157791260-3b66dd4c-6600-4a83-8c35-59cb9673d25a.png)

**Comment by euwbah** [comment]
Fixed in 14e62be5d680816149c232d8b2e0d51c4c2718bb
