### ISSUE TITLE
Arrow keys not working!

### ISSUE THREAD

**Issue by wyattjohnsonbro** [euwbah/musescore-n-tet-plugins#39]
So, I was trying to transpose in 31TET, but when I pressed the arrow keys it just went up the normal one semitone. Is this supposed to happen? If it is, is there a way just to go up one chromatic step in 31TET?

**Comment by bluebear94** [comment]
Did you remember to reassign the keyboard shortcuts according to the README?

**Comment by euwbah** [comment]
closed due to inactivity
