### ISSUE TITLE
Temperaments lower than 12 really don't work that well...

### ISSUE THREAD

**Issue by wyattjohnsonbro** [euwbah/musescore-n-tet-plugins#40]
So, I was trying to mess in 3tet because I find it somewhat interesting and it was really clunky and hard to work with, and some notes just did not work as the tonic. Is this an issue on my end or this a plugin-wide issue?

**Comment by Trebor-Huang** [comment]
Isn't it simpler to use 3 notes out of 12TET? For 5 or 7 TET you can similarly try 15TET and 14TET instead, respectively.

**Comment by bluebear94** [comment]
15edo notates 5edo notes the same as 5edo (and the same applies for 14edo with 7edo).

**Comment by euwbah** [comment]
This project is deprecated, see https://github.com/euwbah/musescore-xen-tuner/ which should do a much better job.
