### ISSUE TITLE
Plugin needs a Massive Update

### ISSUE THREAD

**Issue by DaffodilAura** [euwbah/musescore-n-tet-plugins#43]
Because of the new developments concerning Syntonic-Rastmic Subchroma notation (see https://en.xen.wiki/w/Syntonic-rastmic_subchroma_notation for details) and this system's ability to notate higher systems such as 159edo and 311edo, this plugin needs a serious rework and enhancement in order to reach and cover EDOs like these, and needs to incorporate Syntonic-Rastmic Subchroma notation in order to do so.  Flora Canou and I were both involved in the development of Syntonic-Rastmic Subchroma notation, and since Flora is also involved in the development of this plugin, I think we could make things work, at least for MuseScore 4.

I should also point out that Ocktophonie has given the go-ahead for the MuseScore community to give MuseScore the capability of allowing one to define their own custom tonality systems with as many divisions as they want and define their own glyphs as accidentals without them having to be in the font set.

**Comment by euwbah** [comment]
This feature, and a lot more, is supported in the successor to this plugin: https://github.com/euwbah/musescore-xen-tuner/
